check commands with loop, use long parameter names for understandability

diff --git a/provisioning/roles/motd/files/etc/update-motd.d/10-neofetch b/provisioning/roles/motd/files/etc/update-motd.d/10-neofetch
--- a/provisioning/roles/motd/files/etc/update-motd.d/10-neofetch
+++ b/provisioning/roles/motd/files/etc/update-motd.d/10-neofetch
@@ -16,10 +16,19 @@
 # limitations under the License.                                            #
 #############################################################################
 
-if [[ $(command -v neofetch 2>/dev/null) ]]
-then
-    $(command -v neofetch) --config "/usr/local/etc/neofetch/config.conf"
-else
-    echo -e "\e[01;31mcould not find command 'neofetch'.\e[0m"
-    exit 1
-fi
+command_list=(neofetch)
+checkCommands()
+{
+    for current_command in "${command_list[@]}"
+    do
+        if [[ ! $(command -v ${current_command} 2>/dev/null) ]]
+        then
+            echo -e "\e[01;31mcould not find command '${current_command}'.\e[0m"
+            exit 1
+        fi
+    done
+}
+
+checkCommands
+
+$(command -v neofetch) --config "/usr/local/etc/neofetch/config.conf"
diff --git a/provisioning/roles/motd/files/etc/update-motd.d/20-need-upgrade b/provisioning/roles/motd/files/etc/update-motd.d/20-need-upgrade
--- a/provisioning/roles/motd/files/etc/update-motd.d/20-need-upgrade
+++ b/provisioning/roles/motd/files/etc/update-motd.d/20-need-upgrade
@@ -16,21 +16,30 @@
 # limitations under the License.                                            #
 #############################################################################
 
-if [[ $(command -v apt-get 2>/dev/null) ]]
+command_list=(apt-get awk sort wc)
+checkCommands()
+{
+    for current_command in "${command_list[@]}"
+    do
+        if [[ ! $(command -v ${current_command} 2>/dev/null) ]]
+        then
+            echo -e "\e[01;31mcould not find command '${current_command}'.\e[0m"
+            exit 1
+        fi
+    done
+}
+
+checkCommands
+
+upgradeable_package_count=$($(command -v apt-get) --simulate --quiet=2 upgrade | $(command -v awk) '{ print $2 }' | $(command -v sort) -u | $(command -v wc) -l)
+removable_package_count=$($(command -v apt-get) --simulate --quiet=2 autoremove | $(command -v awk) '{ print $2 }' | $(command -v sort) -u | $(command -v wc) -l)
+
+if (( ${removable_package_count} > 0 ))
 then
-    upgradeable_package_count=$($(command -v apt-get) -s -qq upgrade | awk '{ print $2 }' | sort -u | wc -l)
-    removable_package_count=$($(command -v apt-get) -s -qq autoremove | awk '{ print $2 }' | sort -u | wc -l)
+    echo -e "\e[01;33m[${removable_package_count}] dependency packages are not needed anymore! (execute as root: $(command -v apt-get) autoremove)\e[0m"
+fi
 
-    if (( ${removable_package_count} > 0 ))
-    then
-        echo -e "\e[01;33m[${removable_package_count}] dependency packages are not needed anymore! (execute as root: $(command -v apt-get) autoremove)\e[0m"
-    fi
-
-    if (( ${upgradeable_package_count} > 0 ))
-    then
-        echo -e "\e[01;31;5m[${upgradeable_package_count}] packages still need to be upgraded!\e[0m \e[01;31m(execute as root: $(command -v apt-get) upgrade)\e[0m"
-    fi
-else
-    echo -e "\e[01;31mcould not find command 'apt-get'.\e[0m"
-    exit 1
+if (( ${upgradeable_package_count} > 0 ))
+then
+    echo -e "\e[01;31;5m[${upgradeable_package_count}] packages still need to be upgraded!\e[0m \e[01;31m(execute as root: $(command -v apt-get) upgrade)\e[0m"
 fi
diff --git a/provisioning/roles/motd/files/etc/update-motd.d/30-restart-daemons b/provisioning/roles/motd/files/etc/update-motd.d/30-restart-daemons
--- a/provisioning/roles/motd/files/etc/update-motd.d/30-restart-daemons
+++ b/provisioning/roles/motd/files/etc/update-motd.d/30-restart-daemons
@@ -16,16 +16,25 @@
 # limitations under the License.                                            #
 #############################################################################
 
-DEBIAN_FRONTEND="noninteractive"
-if [[ $(command -v needrestart 2>/dev/null) ]]
-then
-    restart_daemon_count=$($(command -v needrestart) -vnlr l 2>/dev/null | $(command -v grep) -c " restart ")
+command_list=(grep needrestart)
+checkCommands()
+{
+    for current_command in "${command_list[@]}"
+    do
+        if [[ ! $(command -v ${current_command} 2>/dev/null) ]]
+        then
+            echo -e "\e[01;31mcould not find command '${current_command}'.\e[0m"
+            exit 1
+        fi
+    done
+}
 
-    if (( ${restart_daemon_count} > 0 ))
-    then
-        echo -e "\e[01;31;5m[${restart_daemon_count}] daemons are still using old libraries and need to be restarted!\e[0m \e[01;31m(execute as root: $(command -v needrestart))\e[0m"
-    fi
-else
-    echo -e "\e[01;31mcould not find command 'needrestart'.\e[0m"
-    exit 1
+checkCommands
+
+DEBIAN_FRONTEND="noninteractive"
+restart_daemon_count=$($(command -v needrestart) -vnlr l 2>/dev/null | $(command -v grep) -c " restart ")
+
+if (( ${restart_daemon_count} > 0 ))
+then
+    echo -e "\e[01;31;5m[${restart_daemon_count}] daemons are still using old libraries and need to be restarted!\e[0m \e[01;31m(execute as root: $(command -v needrestart))\e[0m"
 fi
diff --git a/provisioning/roles/motd/files/etc/update-motd.d/40-need-reboot b/provisioning/roles/motd/files/etc/update-motd.d/40-need-reboot
--- a/provisioning/roles/motd/files/etc/update-motd.d/40-need-reboot
+++ b/provisioning/roles/motd/files/etc/update-motd.d/40-need-reboot
@@ -16,16 +16,25 @@
 # limitations under the License.                                            #
 #############################################################################
 
-if [[ $(command -v needrestart 2>/dev/null) && $(command -v grep 2>/dev/null) && $(command -v reboot 2>/dev/null) ]]
-then
-    DEBIAN_FRONTEND="noninteractive"
-    need_reboot=$(echo | $(command -v needrestart) -vnk 2>/dev/null | $(command -v grep) "Pending kernel upgrade")
+command_list=(grep needrestart reboot shutdown)
+checkCommands()
+{
+    for current_command in "${command_list[@]}"
+    do
+        if [[ ! $(command -v ${current_command} 2>/dev/null) ]]
+        then
+            echo -e "\e[01;31mcould not find command '${current_command}'.\e[0m"
+            exit 1
+        fi
+    done
+}
 
-    if [[ -n "${need_reboot}" ]]
-    then
-        echo -e "\e[01;31mpending kernel upgrade:\e[0m \e[01;31;5ma reboot is required to use a newly installed kernel!\e[0m \e[01;31m(execute as root: $(command -v reboot))\e[0m"
-    fi
-else
-    echo -e "\e[01;31mcould not find command 'needrestart', 'grep' or 'reboot'.\e[0m"
-    exit 1
+checkCommands
+
+DEBIAN_FRONTEND="noninteractive"
+need_reboot=$(echo | $(command -v needrestart) -vnk 2>/dev/null | $(command -v grep) "Pending kernel upgrade")
+
+if [[ -n "${need_reboot}" ]]
+then
+    echo -e "\e[01;31mpending kernel upgrade:\e[0m \e[01;31;5ma reboot is required to use a newly installed kernel!\e[0m \e[01;31m(execute as root: $(command -v reboot))\e[0m"
 fi
